[phases.setup]
nixPkgs = ["python3", "gcc"]
nixLibs = ["zlib", "stdenv.cc.cc.lib"]
aptPkgs = ["curl", "wget"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "python manage.py migrate && gunicorn -c gunicorn.conf.py myproject.wsgi:application"

[variables]
PYTHONPATH = "/app"
PIP_DEFAULT_TIMEOUT = "100"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
PIP_NO_CACHE_DIR = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONFAULTHANDLER = "1"
PYTHONHASHSEED = "random"
PYTHONUNBUFFERED = "1"