services:
  - type: web
    name: django-batch-image-downloader
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: django-batch-db
          property: connectionString

databases:
  - name: django-batch-db
    databaseName: django_batch_db
    user: django_user