# Generated by Django 5.2.6 on 2025-09-10 22:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_products', models.IntegerField(default=0)),
                ('total_images', models.IntegerField(default=0)),
                ('completed_images', models.IntegerField(default=0)),
                ('failed_images', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='PENDING', max_length=20)),
                ('image_count', models.IntegerField(default=0)),
                ('downloaded_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('bytes_downloaded', models.BigIntegerField(default=0)),
                ('zip_ready', models.BooleanField(default=False)),
                ('zip_size', models.BigIntegerField(default=0)),
                ('zip_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='batch_downloader.downloadjob')),
            ],
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DOWNLOADING', 'Downloading'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='batch_downloader.productbatch')),
            ],
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['status'], name='batch_downl_status_3b4524_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['created_at'], name='batch_downl_created_dce25c_idx'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['job', 'status'], name='batch_downl_job_id_fded74_idx'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['status'], name='batch_downl_status_be774c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productbatch',
            unique_together={('job', 'product_number')},
        ),
        migrations.AddIndex(
            model_name='imageitem',
            index=models.Index(fields=['product_batch', 'status'], name='batch_downl_product_c53d85_idx'),
        ),
        migrations.AddIndex(
            model_name='imageitem',
            index=models.Index(fields=['status'], name='batch_downl_status_789415_idx'),
        ),
        migrations.AddIndex(
            model_name='imageitem',
            index=models.Index(fields=['checksum_sha256'], name='batch_downl_checksu_843644_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imageitem',
            unique_together={('product_batch', 'url')},
        ),
    ]
