# Generated by Django 5.2.6 on 2025-09-10 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_downloader', '0001_initial'),
    ]

    operations = [
    ]
