# Generated by Django 5.2.6 on 2025-09-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_downloader', '0002_auto_20250911_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
